name: "TASTER"
description: "Training Attention Switching for Temper Episode Reduction"

url: "http://nrobb.github.io/taster-site"

paginate: 10

markdown: kramdown
highlighter: rouge
permalink: pretty

exclude: []
